### ISSUE TITLE
v8 profiler is blocking fidelity update to node 8x

### ISSUE THREAD

**Issue by helio-frota** [bucharest-gold/fidelity#45]
```
npm ERR! @risingstack/v8-profiler@5.7.9 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @risingstack/v8-profiler@5.7.9 install script.
```

**Comment by helio-frota** [comment]
Related to https://github.com/bucharest-gold/entente/issues/161

**Comment by helio-frota** [comment]
We get this error when running `npm install`

**Comment by danbev** [comment]
> We get this error when running npm install

I've tried to reproduce this with `8.1.0` but I'm not seeing the error reported. Are there any additional changes needed?

**Comment by helio-frota** [comment]
weird... please look:

```
✔ ~/dev/fidelity [master|✔] 
10:25 $ npm install
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> @risingstack/v8-profiler@5.7.9 preinstall /home/hf/dev/fidelity/node_modules/@risingstack/v8-profiler
> node -e 'process.exit(0)'

npm WARN prefer global sqwish@0.2.2 should be installed with -g
npm WARN prefer global marked@0.3.6 should be installed with -g

> @risingstack/v8-profiler@5.7.9 install /home/hf/dev/fidelity/node_modules/@risingstack/v8-profiler
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://oss.risingstack.com/repo/v1/@risingstack/profiler/dist/v5.7.9/node-v57-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for @risingstack/v8-profiler@5.7.9 and node@8.1.0 (node-v57 ABI) (falling back to source compile with node-gyp) 
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory '/home/hf/dev/fidelity/node_modules/@risingstack/v8-profiler/build'
  CXX(target) Release/obj.target/profiler/src/profiler.o
make: g++: Command not found
profiler.target.mk:103: recipe for target 'Release/obj.target/profiler/src/profiler.o' failed
make: *** [Release/obj.target/profiler/src/profiler.o] Error 127
make: Leaving directory '/home/hf/dev/fidelity/node_modules/@risingstack/v8-profiler/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/hf/.nvm/versions/node/v8.1.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Linux 4.11.3-200.fc25.x86_64
gyp ERR! command "/home/hf/.nvm/versions/node/v8.1.0/bin/node" "/home/hf/.nvm/versions/node/v8.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/hf/dev/fidelity/node_modules/@risingstack/v8-profiler/build/@risingstack/profiler/v5.7.9/node-v57-linux-x64/profiler.node" "--module_name=profiler" "--module_path=/home/hf/dev/fidelity/node_modules/@risingstack/v8-profiler/build/@risingstack/profiler/v5.7.9/node-v57-linux-x64"
gyp ERR! cwd /home/hf/dev/fidelity/node_modules/@risingstack/v8-profiler
gyp ERR! node -v v8.1.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/hf/.nvm/versions/node/v8.1.0/bin/node /home/hf/.nvm/versions/node/v8.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/hf/dev/fidelity/node_modules/@risingstack/v8-profiler/build/@risingstack/profiler/v5.7.9/node-v57-linux-x64/profiler.node --module_name=profiler --module_path=/home/hf/dev/fidelity/node_modules/@risingstack/v8-profiler/build/@risingstack/profiler/v5.7.9/node-v57-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/hf/dev/fidelity/node_modules/@risingstack/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:125:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:887:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
node-pre-gyp ERR! System Linux 4.11.3-200.fc25.x86_64
node-pre-gyp ERR! command "/home/hf/.nvm/versions/node/v8.1.0/bin/node" "/home/hf/dev/fidelity/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/hf/dev/fidelity/node_modules/@risingstack/v8-profiler
node-pre-gyp ERR! node -v v8.1.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.35
node-pre-gyp ERR! not ok 
Failed to execute '/home/hf/.nvm/versions/node/v8.1.0/bin/node /home/hf/.nvm/versions/node/v8.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/hf/dev/fidelity/node_modules/@risingstack/v8-profiler/build/@risingstack/profiler/v5.7.9/node-v57-linux-x64/profiler.node --module_name=profiler --module_path=/home/hf/dev/fidelity/node_modules/@risingstack/v8-profiler/build/@risingstack/profiler/v5.7.9/node-v57-linux-x64' (1)
npm WARN eslint-config-standard@10.2.1 requires a peer of eslint-plugin-standard@>=3.0.0 but none was installed.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @risingstack/v8-profiler@5.7.9 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @risingstack/v8-profiler@5.7.9 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hf/.npm/_logs/2017-06-13T13_25_29_824Z-debug.log
✘-1 ~/dev/fidelity [master|✔] 
```

And this one is for genet project:

```
✔ ~/dev/genet [master|✔] 
10:23 $ npm install

> @risingstack/v8-profiler@5.7.9 preinstall /home/hf/dev/genet/node_modules/@risingstack/v8-profiler
> node -e 'process.exit(0)'


> @risingstack/v8-profiler@5.7.9 install /home/hf/dev/genet/node_modules/@risingstack/v8-profiler
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://oss.risingstack.com/repo/v1/@risingstack/profiler/dist/v5.7.9/node-v57-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for @risingstack/v8-profiler@5.7.9 and node@8.1.0 (node-v57 ABI) (falling back to source compile with node-gyp) 
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory '/home/hf/dev/genet/node_modules/@risingstack/v8-profiler/build'
  CXX(target) Release/obj.target/profiler/src/profiler.o
make: g++: Command not found
profiler.target.mk:103: recipe for target 'Release/obj.target/profiler/src/profiler.o' failed
make: *** [Release/obj.target/profiler/src/profiler.o] Error 127
make: Leaving directory '/home/hf/dev/genet/node_modules/@risingstack/v8-profiler/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/hf/.nvm/versions/node/v8.1.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Linux 4.11.3-200.fc25.x86_64
gyp ERR! command "/home/hf/.nvm/versions/node/v8.1.0/bin/node" "/home/hf/.nvm/versions/node/v8.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/hf/dev/genet/node_modules/@risingstack/v8-profiler/build/@risingstack/profiler/v5.7.9/node-v57-linux-x64/profiler.node" "--module_name=profiler" "--module_path=/home/hf/dev/genet/node_modules/@risingstack/v8-profiler/build/@risingstack/profiler/v5.7.9/node-v57-linux-x64"
gyp ERR! cwd /home/hf/dev/genet/node_modules/@risingstack/v8-profiler
gyp ERR! node -v v8.1.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/hf/.nvm/versions/node/v8.1.0/bin/node /home/hf/.nvm/versions/node/v8.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/hf/dev/genet/node_modules/@risingstack/v8-profiler/build/@risingstack/profiler/v5.7.9/node-v57-linux-x64/profiler.node --module_name=profiler --module_path=/home/hf/dev/genet/node_modules/@risingstack/v8-profiler/build/@risingstack/profiler/v5.7.9/node-v57-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/hf/dev/genet/node_modules/@risingstack/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:125:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:887:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
node-pre-gyp ERR! System Linux 4.11.3-200.fc25.x86_64
node-pre-gyp ERR! command "/home/hf/.nvm/versions/node/v8.1.0/bin/node" "/home/hf/dev/genet/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/hf/dev/genet/node_modules/@risingstack/v8-profiler
node-pre-gyp ERR! node -v v8.1.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.35
node-pre-gyp ERR! not ok 
Failed to execute '/home/hf/.nvm/versions/node/v8.1.0/bin/node /home/hf/.nvm/versions/node/v8.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/hf/dev/genet/node_modules/@risingstack/v8-profiler/build/@risingstack/profiler/v5.7.9/node-v57-linux-x64/profiler.node --module_name=profiler --module_path=/home/hf/dev/genet/node_modules/@risingstack/v8-profiler/build/@risingstack/profiler/v5.7.9/node-v57-linux-x64' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @risingstack/v8-profiler@5.7.9 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @risingstack/v8-profiler@5.7.9 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hf/.npm/_logs/2017-06-13T13_24_27_587Z-debug.log
✘-1 ~/dev/genet [master|✔] 
```

```
✘-1 ~/dev/genet [master|✔] 
10:24 $ node --version
v8.1.0
✔ ~/dev/genet [master|✔] 
```

**Comment by danbev** [comment]
@helio-frota Thanks, I removed my `node_modules` directory and now I'm seeing the error 👍

**Comment by helio-frota** [comment]
sorry was my fault:

```
  CXX(target) Release/obj.target/profiler/src/profiler.o
make: g++: Command not found
profiler.target.mk:103: recipe 
```
after install worked
```
[hf@t440 ~]$ sudo dnf install gcc-c++
```

going to close
