### ISSUE TITLE
Build error on Windows 10

### ISSUE THREAD

**Issue by helio-frota** [bucharest-gold/fidelity#84]
Related with v8-profiler

First, need python 2.7x installed, otherwise:
```
$ npm it
npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha1-Yi4y6CSItJJ5EUpPns9F581rulU= integrity checksum failed when using sha1: wanted sha1-Yi4y6CSItJJ5EUpPns9F581rulU= but got sha512-q4spe4KTfsAS1SUHLO0wz8Qiyf1+vMIAgpRYioFYDMNqKfHQbg+AVDH3i4fvpl71/P1L0dBl+fQi+P37UYf0ew==. (6052 bytes)
npm WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.

> @risingstack/v8-profiler@5.7.11 preinstall C:\Users\hf\Desktop\dev\fidelity\node_modules\@risingstack\v8-profiler
> node -e 'process.exit(0)'


> fmerge@1.2.0 install C:\Users\hf\Desktop\dev\fidelity\node_modules\fmerge
> node install.js

`fmerge.min.js` created

> @risingstack/v8-profiler@5.7.11 install C:\Users\hf\Desktop\dev\fidelity\node_modules\@risingstack\v8-profiler
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://oss.risingstack.com/repo/v1/@risingstack/profiler/dist/v5.7.11/node-v57-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for @risingstack/v8-profiler@5.7.11 and node@8.9.0 (node-v57 ABI) (falling back to source compile with node-gyp)

C:\Users\hf\Desktop\dev\fidelity\node_modules\@risingstack\v8-profiler>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node "" clean )

C:\Users\hf\Desktop\dev\fidelity\node_modules\@risingstack\v8-profiler>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=C:\Users\hf\Desktop\dev\fidelity\node_modules\@risingstack\v8-profiler\build\@risingstack\profiler\v5.7.11\node-v57-win32-x64\profiler.node --module_name=profiler --module_path=C:\Users\hf\Desktop\dev\fidelity\node_modules\@risingstack\v8-profiler\build\@risingstack\profiler\v5.7.11\node-v57-win32-x64 )  else (node "" configure --fallback-to-build --module=C:\Users\hf\Desktop\dev\fidelity\node_modules\@risingstack\v8-profiler\build\@risingstack\profiler\v5.7.11\node-v57-win32-x64\profiler.node --module_name=profiler --module_path=C:\Users\hf\Desktop\dev\fidelity\node_modules\@risingstack\v8-profiler\build\@risingstack\profiler\v5.7.11\node-v57-win32-x64 )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\hf\AppData\Local\Programs\Python\Python36-32\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\hf\\Desktop\\dev\\fidelity\\node_modules\\@risingstack\\v8-profiler\\build\\@risingstack\\profiler\\v5.7.11\\node-v57-win32-x64\\profiler.node" "--module_name=profiler" "--module_path=C:\\Users\\hf\\Desktop\\dev\\fidelity\\node_modules\\@risingstack\\v8-profiler\\build\\@risingstack\\profiler\\v5.7.11\\node-v57-win32-x64"
gyp ERR! cwd C:\Users\hf\Desktop\dev\fidelity\node_modules\@risingstack\v8-profiler
gyp ERR! node -v v8.9.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Users\hf\Desktop\dev\fidelity\node_modules\@risingstack\v8-profiler\build\@risingstack\profiler\v5.7.11\node-v57-win32-x64\profiler.node --module_name=profiler --module_path=C:\Users\hf\Desktop\dev\fidelity\node_modules\@risingstack\v8-profiler\build\@risingstack\profiler\v5.7.11\node-v57-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\hf\Desktop\dev\fidelity\node_modules\@risingstack\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Windows_NT 10.0.16299
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\hf\\Desktop\\dev\\fidelity\\node_modules\\@risingstack\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\hf\Desktop\dev\fidelity\node_modules\@risingstack\v8-profiler
node-pre-gyp ERR! node -v v8.9.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.35
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Users\hf\Desktop\dev\fidelity\node_modules\@risingstack\v8-profiler\build\@risingstack\profiler\v5.7.11\node-v57-win32-x64\profiler.node --module_name=profiler --module_path=C:\Users\hf\Desktop\dev\fidelity\node_modules\@risingstack\v8-profiler\build\@risingstack\profiler\v5.7.11\node-v57-win32-x64' (1)
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @risingstack/v8-profiler@5.7.11 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @risingstack/v8-profiler@5.7.11 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hf\AppData\Roaming\npm-cache\_logs\2017-11-10T11_02_20_284Z-debug.log
```

After python installed:

```
$ npm it

> @risingstack/v8-profiler@5.7.11 preinstall C:\Users\hf\Desktop\dev\fidelity\node_modules\@risingstack\v8-profiler
> node -e 'process.exit(0)'


> @risingstack/v8-profiler@5.7.11 install C:\Users\hf\Desktop\dev\fidelity\node_modules\@risingstack\v8-profiler
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://oss.risingstack.com/repo/v1/@risingstack/profiler/dist/v5.7.11/node-v57-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for @risingstack/v8-profiler@5.7.11 and node@8.9.0 (node-v57 ABI) (falling back to source compile with node-gyp)

C:\Users\hf\Desktop\dev\fidelity\node_modules\@risingstack\v8-profiler>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node "" clean )

C:\Users\hf\Desktop\dev\fidelity\node_modules\@risingstack\v8-profiler>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=C:\Users\hf\Desktop\dev\fidelity\node_modules\@risingstack\v8-profiler\build\@risingstack\profiler\v5.7.11\node-v57-win32-x64\profiler.node --module_name=profiler --module_path=C:\Users\hf\Desktop\dev\fidelity\node_modules\@risingstack\v8-profiler\build\@risingstack\profiler\v5.7.11\node-v57-win32-x64 )  else (node "" configure --fallback-to-build --module=C:\Users\hf\Desktop\dev\fidelity\node_modules\@risingstack\v8-profiler\build\@risingstack\profiler\v5.7.11\node-v57-win32-x64\profiler.node --module_name=profiler --module_path=C:\Users\hf\Desktop\dev\fidelity\node_modules\@risingstack\v8-profiler\build\@risingstack\profiler\v5.7.11\node-v57-win32-x64 )

C:\Users\hf\Desktop\dev\fidelity\node_modules\@risingstack\v8-profiler>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" build --fallback-to-build --module=C:\Users\hf\Desktop\dev\fidelity\node_modules\@risingstack\v8-profiler\build\@risingstack\profiler\v5.7.11\node-v57-win32-x64\profiler.node --module_name=profiler --module_path=C:\Users\hf\Desktop\dev\fidelity\node_modules\@risingstack\v8-profiler\build\@risingstack\profiler\v5.7.11\node-v57-win32-x64 )  else (node "" build --fallback-to-build --module=C:\Users\hf\Desktop\dev\fidelity\node_modules\@risingstack\v8-profiler\build\@risingstack\profiler\v5.7.11\node-v57-win32-x64\profiler.node --module_name=profiler --module_path=C:\Users\hf\Desktop\dev\fidelity\node_modules\@risingstack\v8-profiler\build\@risingstack\profiler\v5.7.11\node-v57-win32-x64 )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB4132: The tools version "2.0" is unrecognized. Available tools versions are "4.0".
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\hf\\Desktop\\dev\\fidelity\\node_modules\\@risingstack\\v8-profiler\\build\\@risingstack\\profiler\\v5.7.11\\node-v57-win32-x64\\profiler.node" "--module_name=profiler" "--module_path=C:\\Users\\hf\\Desktop\\dev\\fidelity\\node_modules\\@risingstack\\v8-profiler\\build\\@risingstack\\profiler\\v5.7.11\\node-v57-win32-x64"
gyp ERR! cwd C:\Users\hf\Desktop\dev\fidelity\node_modules\@risingstack\v8-profiler
gyp ERR! node -v v8.9.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\Users\hf\Desktop\dev\fidelity\node_modules\@risingstack\v8-profiler\build\@risingstack\profiler\v5.7.11\node-v57-win32-x64\profiler.node --module_name=profiler --module_path=C:\Users\hf\Desktop\dev\fidelity\node_modules\@risingstack\v8-profiler\build\@risingstack\profiler\v5.7.11\node-v57-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\hf\Desktop\dev\fidelity\node_modules\@risingstack\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Windows_NT 10.0.16299
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\hf\\Desktop\\dev\\fidelity\\node_modules\\@risingstack\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\hf\Desktop\dev\fidelity\node_modules\@risingstack\v8-profiler
node-pre-gyp ERR! node -v v8.9.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.35
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\Users\hf\Desktop\dev\fidelity\node_modules\@risingstack\v8-profiler\build\@risingstack\profiler\v5.7.11\node-v57-win32-x64\profiler.node --module_name=profiler --module_path=C:\Users\hf\Desktop\dev\fidelity\node_modules\@risingstack\v8-profiler\build\@risingstack\profiler\v5.7.11\node-v57-win32-x64' (1)
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @risingstack/v8-profiler@5.7.11 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @risingstack/v8-profiler@5.7.11 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hf\AppData\Roaming\npm-cache\_logs\2017-11-10T11_09_35_790Z-debug.log
```

Related to bucharest-gold/entente#179

**Comment by helio-frota** [comment]
I'm going to close this, because is related to v8-profiler and node 8.9.0 , not related with fidelity and windows 10.
`Pre-built binaries not found for @risingstack/v8-profiler@5.7.11 and node@8.9.0 (node-v57 ABI) (falling back to source compile with node-gyp)
`
The same thing happened with `genet`.
